apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-webserver-argocd
spec:
  selector:
    matchLabels:
      app: mywebserver
  replicas: 2
  template:
    metadata:
      labels:
        app: mywebserver
    spec:
      containers:
      - name: webserver-container
        image: gcr.io/searce-playground-v1/shubham-versioning:f8b760e 
        ports:
        - containerPort: 80
